'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class customer
    Public Property customerId As Integer
    Public Property firstName As String
    Public Property lastName As String
    Public Property street As String
    Public Property city As String
    Public Property postalCode As String
    Public Property phone As String
    Public Property extension As String

End Class
